version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - '50001:3000'
    env_file:
      - ./server/.env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    ports:
      - '50002:80'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand({ ping: 1 })']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
